name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cleanup Workspace
        run: |
          rm -rf build
          rm -rf .git/refs/heads/main  # A veces da problemas
          ls -R # Muestra los archivos para que veas en el log si logo2.png está ahí

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Flet & Dependencies
        run: |
          pip install -r requirements.txt
          pip install flet

      - name: Accept Android Licenses
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses

      - name: Build APK
        run: |
          flet build apk --verbose --include-packages flet

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: AppVisitas.apk
          path: build/apk/app-release.apk
